[package]
name = "history-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path="../common" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.143", features = ["unbounded_depth"] }
